# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="Install software by chicks with brew/homebrew 🐣☕"
REPO_LICENSE=""
REPO_TOPICS="bash-script,homebrew-tap,shell-utilities"

# URLs section
REPO_GIT_SSH="git@github.com:chicks-net/homebrew-chicks.git"
REPO_WEB_URL="https://github.com/chicks-net/homebrew-chicks"

# Derived values
REPO_ORG_NAME="chicks-net"
REPO_REPO_NAME="homebrew-chicks"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="true"
FLAG_CLAUDE_REVIEW="true"
FLAG_COPILOT_REVIEW="true"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "bash-script"
    "homebrew-tap"
    "shell-utilities"
)
