# .repo.toml

[about]
description = "Install software by chicks with brew/homebrew 🐣☕"
topics = ["bash-script", "homebrew-tap", "shell-utilities"]

[urls]
git_ssh = "git@github.com:chicks-net/homebrew-chicks.git"
web_url = "https://github.com/chicks-net/homebrew-chicks"

[flags]
claude = false
claude-review = false
copilot-review = false
standard-release = true
